spring:
  application:
    name: taro-web-app
  main:
    web-application-type: reactive


  r2dbc:
    url: r2dbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

openai:
  apiKey: ${OPENAI_API_KEY}

taro:
  deck-size: ${DECK_SIZE:78}
  spread-cards-num: ${SPREAD_CARDS_NUM:3}
  card:
    path-prefix: ${PATH_PREFIX}