DB_URL: localhost:5432/taro
DB_USERNAME: taro
DB_PASSWORD: taro

OPENAI_MOCKED: true
OPENAI_API_KEY: ${OPENAI_API_KEY}

PATH_PREFIX: /cards/

logging:
  level:
    dalia.daniele.telegram.taro_web_app.llm.OpenAiLlm: DEBUG